[package]
name = "universe-vm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
universe-compiler = { path = "../universe-compiler" }
universe-core = { path = "../universe-core" }
universe-ir = { path = "../universe-ir" }

[dev-dependencies]
serde_json.workspace = true
tempfile = "3"
universe-query = { path = "../universe-query" }
universe-store = { path = "../universe-store" }
