import type {
  EnergyTransfer,
  MaterializedEntity,
  MaterializedRelation,
  Vector3,
  VisualMaterial
} from "./contracts";
import { NEUTRAL_DYNAMICS } from "./entity-dynamics";
import type { UniverseView } from "./universe-state";
import projection from "./fixtures/neighborhood-projection.json";

// A renderer projection of the EXECUTED neighborhood arc. BOTH halves are now
// real: the ENERGY is measured:semantic + executed as BehaviorBonds, and the 3D
// POSITIONS come from the universe-assets LAYOUT ENGINE (force-directed,
// energy-weighted). The data is generated by:
//   cargo run -p universe-e2e --bin neighborhood_projection
// -> src/fixtures/neighborhood-projection.json (do not hand-edit; regenerate).

function vec3(position: readonly number[]): Vector3 {
  return [position[0] ?? 0, position[1] ?? 0, position[2] ?? 0];
}

function material(
  color: string,
  emissive: string,
  emissiveIntensity: number,
  scale: number
): VisualMaterial {
  return { color, emissive, emissiveIntensity, opacity: 0.92, scale };
}

export function neighborhoodFixtureUniverse(): UniverseView {
  const entities = new Map<string, MaterializedEntity>();
  const relations = new Map<string, MaterializedRelation>();
  const transfers = new Map<string, EnergyTransfer>();

  const here: MaterializedEntity = {
    id: projection.start.id,
    generation: 0,
    position: vec3(projection.start.position),
    visual: {
      primitive: "pulsing_core",
      motion: "outward_pulse",
      material: material("#ffd479", "#ffb020", 2.6, 1.2)
    },
    dynamics: NEUTRAL_DYNAMICS
  };
  entities.set(here.id, here);

  const maxEnergy = Math.max(
    1,
    ...projection.candidates.map((candidate) => candidate.energy)
  );

  projection.candidates.forEach((candidate, index) => {
    const norm = candidate.energy / maxEnergy;
    const strongest = candidate.strongest;
    const color = strongest ? "#7ef7c8" : "#8fd0ff";
    const emissive = strongest ? "#33ffa0" : "#3a9cff";

    entities.set(candidate.id, {
      id: candidate.id,
      generation: 0,
      position: vec3(candidate.position),
      visual: {
        primitive: strongest ? "open_polyhedral_attractor" : "faceted_router",
        motion: "through_flow",
        material: material(color, emissive, 1.4 + norm, 0.7 + 0.6 * norm)
      },
      dynamics: NEUTRAL_DYNAMICS
    });

    const relationId = `neighborhood:bond:${index}`;
    relations.set(relationId, {
      id: relationId,
      source: here.id,
      target: candidate.id,
      visual: {
        primitive: "luminous_chain",
        material: material("#bfe6ff", "#3a9cff", 1.0 + norm, 1),
        width: 0.04 + 0.12 * norm,
        laneSeparation: 0.08
      }
    });

    const transferId = `neighborhood:transfer:${index}`;
    transfers.set(transferId, {
      transferId,
      executionId: "neighborhood-arc",
      intentionId: `bond:${candidate.predicate}`,
      revision: 2,
      tick: 1,
      relationId,
      source: here.id,
      target: candidate.id,
      direction: "source_to_target",
      polarity: "support",
      energy: candidate.energy,
      gate: 1,
      outcome: "measured",
      epistemic: "measured",
      visual: {
        primitive: "energy_packet",
        color,
        emissive,
        emissiveIntensity: 1.6 + norm,
        radius: 0.18 + 0.5 * norm,
        opacity: 0.9,
        durationMs: 900 + Math.round(600 * norm)
      }
    });
  });

  return {
    revision: 2,
    sequence: 0,
    synchronized: true,
    entities,
    relations,
    transfers,
    control: { kind: "observer" },
    // The neighborhood glide is a static observer projection: no affordances are
    // offered here, and `[]` is the honest "nothing offered" default (never
    // `undefined`), matching every other materialized view.
    available_actions: []
  };
}
